conversion:
  dpi: 300
  format: "png"        # png or jpg
  color_mode: "RGB"    # RGB or L
  resize: "1000x1000"  # WIDTHxHEIGHT or null for no resize

training:
  model_type: "ultralytics"   # ultralytics | rfdetr
  model: "yolov8n.pt"         # used when model_type=ultralytics
  epochs: 100
  batch: 16
  imgsz: 640
  optimizer: "auto"
  patience: 50
  cache: true
  multi_scale: false
  workers: 4
  device: ""           # e.g., "cpu", "0" for first GPU; empty = auto
  project: "reports/ultralytics"
  name: "exp"
  onnx_export: true
  onnx_opset: 12
  onnx_dynamic: true

mlflow:
  enabled: true
  tracking_uri: ""             # leave empty for local ./mlruns, or set to http(s) URI
  experiment_name: "YOLO-DVC"
  run_name: "${training.name}"  # defaults to training.name if left as-is
  registry_uri: ""             # optional model registry URI
  log_artifacts: true          # log models and reports as artifacts

rfdetr:
  dataset_dir: "data/raw"     # expects COCO-format splits under this dir
  output_dir: "reports/rfdetr_runs"
  epochs: 50
  batch_size: 4
  grad_accum_steps: 4
  lr: 1e-4


